# -----------------------------
# Copyright - This the Most Detailed Code fully written by the Owner of www.amanchourasia.in! This Code is fully Copyrighted by the Owner of www.amanchourasia.in! No one else wrote this code before!

# Disclaimer - This Code Contains Links, I am not responsible of ay damage caused by the link present in the code.

# About the Code: This the Most Detailed Code written in Python to Generate a Random Number, which is going to be stored in a Variable Name number, and the last step will be to print the code.

# Author: Aman Chourasia
# Website: www.amanchourasia.in

# Date of Creation: 22nd July 2021
# -----------------------------

# The Code Starts Here!

# Imported Random Module if you haven't installed it, then what are you waiting for? Go just open the terminal and type pip install random. I am not responsible for any errors caused during the installation of the Random Module. 
# If you want a detailed guide you can head on to this link - https://bit.ly/3y2jrNE.=
import random

# Created a Number Variable which will store the random number, which will be generated by the randint function  in the random module. There you'll also see that it is given (0,10) this mesans that the value stored in the number variable will be greater than 0 and less then 10. You can change the number as per your need. Once again I am telling that this Code is made possible using the Random Module.
number = random.randint(0, 10)

# Here, at the last step we are using the print() function to print the random number generated by the Random Module. This is a very easy step and the last line of the program.
print(number)

# The Code Ends Here...
